module.exports = {
  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503
  },
  ERROR_CODES: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTH_ERROR: 'AUTH_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
    DUPLICATE_ERROR: 'DUPLICATE_ERROR',
    RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
    SERVER_ERROR: 'SERVER_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR'
  },
  AUTH: {
    TOKEN_TYPES: {
      ACCESS: 'access',
      REFRESH: 'refresh'
    },
    PROVIDERS: {
      GOOGLE: 'google',
      GITHUB: 'github'
    }
  },
  CACHE: {
    TTL: {
      SHORT: 300,
      MEDIUM: 1800,
      LONG: 3600
    }
  },
  VALIDATION: {
    PAGINATION: {
      MIN_PAGE: 1,
      MIN_LIMIT: 1,
      MAX_LIMIT: 100,
      DEFAULT_LIMIT: 20
    }
  },
  PATTERNS: {
    EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    OBJECT_ID: /^[0-9a-fA-F]{24}$/
  }
};