export const quotes = [
  "One problem today = one less bug tomorrow. (Probably.)",
  "Solve problems now so your future self doesn't have to Google 'how to reverse a linked list' at 2 AM.",
  "Your brain is like a phone battery – solve a problem, get a little more charge.",
  "DSA daily: because 'trust me bro' doesn't work in technical interviews.",
  "Every problem you solve is another reason to flex in front of your friends. (Not that you would.)",
  "Solve today, impress yourself tomorrow. Or at least confuse yourself a little less.",
  "One problem a day keeps the imposter syndrome… well, it doesn't keep it away, but it helps.",
  "Consistency is like vegetables – not always fun, but future you will be grateful.",
  "Solve problems like you scroll social media – daily, but with less regret.",
  "Another problem solved = another excuse to celebrate with snacks.",
  "Your future job offer is just a bunch of solved problems stacked together. Start stacking.",
  "Think of each problem as a tiny win. Collect enough wins and you've got a victory.",
  "DSA: because 'it works on my machine' doesn't cut it in interviews.",
  "Solve daily, stay humble. Or don't – we won't judge if you do a little victory dance.",
  "One problem at a time. Even Rome wasn't built in a day. (And they didn't have LeetCode.)",
  "The more you solve, the less you panic when someone says 'implement a binary tree'.",
  "Today's struggle = tomorrow's flex. Get solving.",
  "Problems are like onions – they might make you cry, but solving them feels good.",
  "Solve now, brag later. (Or brag now – we're not the boss of you.)",
  "Solve one problem today, and you're one step closer to being a problem‑solving pro.",
  "Daily practice makes you the person who actually *likes* coding interviews.",
  "The more you solve, the less you struggle. (It's like leveling up in real life.)",
  "Every problem you crack is a little win for your brain. Collect them daily.",
  "Consistency > intensity. One problem a day keeps the panic away.",
  "Train your brain like an athlete trains their muscles – one rep at a time.",
  "Problems are just puzzles waiting to be solved. And you love puzzles, right?",
  "Solve daily, stay sharp, and laugh at the bugs later.",
  "A problem a day makes the interviewer say 'okay, you're hired'.",
  "You don't need to be a genius – just someone who solves a little every day.",
  "Small steps, big results. One problem today, mastery tomorrow.",
  "Think of it like brushing your teeth – but for your coding skills.",
  "The secret to being a great problem solver? Solving problems. (Shocker!)",
  "Keep solving, keep growing. And maybe have a snack while you're at it."
];